### ISSUE TITLE
ModelPolisher-2.0.1.jar is not available when running in docker container

### ISSUE THREAD

**Issue by famosab** [draeger-lab/ModelPolisher#105]
I had to download the file separately from the Releases page and save it to the ModelPolisher directory. That was a bit confusing. 

Only installing from the Releases page worked, the Installation instructions given in the ReadMe did not work for me.

**Comment by Schmoho** [comment]
Hey,
so I could not immediately reproduce this, maybe you can help me clear something up.

The ModelPolisher-2.0.1.jar is indeed not provided by the docker image as it is currently on master:
[see here](https://github.com/draeger-lab/ModelPolisher/blob/master/docker/java_docker/Dockerfile#L5), the name of the build artifact is actually `ModelPolisher-2.1-beta.jar`.

This is however in line with [what is in the readme](https://github.com/draeger-lab/ModelPolisher/commit/eaed3e09bac4dc6a77d50b4b68649277295b8c5d). So my first question would be, could you verify what jar you tried to access?

E.g. run `history | grep 'ModelPolisher-2.1.*.jar'`

**Comment by Schmoho** [comment]
This could not be reproduced and the issue is resolved (from a practical point of view).
