### ISSUE TITLE
update README and Wiki

### ISSUE THREAD

**Issue by Schmoho** [draeger-lab/ModelPolisher#115]
The documentation is not very inviting currently.

- in the first paragraph we greet the user with a troubleshooting hint -> can be moved to a troubleshooting page in the wiki
- notes for developers on how to build the project can be moved to the wiki
also, the building instructions reference the `lightJar` gradle task, which our configuration does not include
- "how to cite" groups more naturally with the heading licenses
- we have no user documentation that actually explains what exactly the user can expect the ModelPolisher to do -> wiki page

**Comment by GwennyGit** [comment]
For users who need to install `docker` before using `ModelPolisher` links to the corresponding installation guides would be a nice addition for the documentation. <br>
For example: <br>
How to install `docker`:
- on Linux: https://docs.docker.com/desktop/install/linux-install/
- on Mac: https://docs.docker.com/desktop/install/mac-install/
- on Windows: https://docs.docker.com/desktop/install/windows-install/
