### ISSUE TITLE
COBRAparser and JSONparser failing on current bigg_models

### ISSUE THREAD

**Issue by mephenor** [draeger-lab/ModelPolisher#27]
- JSONparser fails to parse model iJB785.json at formula H70.5616C44.9625O13.1713S0.2669N12.1054R-1.0 (is this a valid chemical formula?)
- COBRAparser fails with "An illegal reflective access operation has occurred. Illegal reflective access by com.jmatio.io.MatFileReader$1.Please consider reporting this to the maintainers of com.jmatio.io.MatFileReader$1". 
Might need to fork this and fix it, if there is no current fork out there

**Comment by zakandrewking** [comment]
which metabolite is that in?

**Comment by mephenor** [comment]
{
"id":"bm_pro_c",
"name":"Protein component of biomass",
"compartment":"c",
"charge":0,
"formula":"H70.5616C44.9625O13.1713S0.2669N12.1054R-1.0"
},

**Comment by zakandrewking** [comment]
there's no formula for it here:

http://bigg.ucsd.edu/models/iJB785/metabolites/bm_pro_c

**Comment by zakandrewking** [comment]
I think we removed those decimal formulae

**Comment by mephenor** [comment]
The formula is still present in https://github.com/SBRG/bigg_models_data/blob/master/models/iJB785.json .

The other issue seems to be related to the Java 9 module system.
With Java 8 COBRAparser works normally

**Comment by matthiaskoenig** [comment]
Json parser is still failing on models. See for instance also example:
```
java -jar ./target/ModelPolisher-noDB-1.7.jar --input="./examples/bigg/e_coli_core.json" --output="./examples/bigg/e_coli_core_json_polished.xml" --annotate-with-bigg=true --host=0.0.0.0 --port=1310 --user=postgres --passwd=postgres --dbname=bigg
```

**Comment by mephenor** [comment]
I will have a look at that

**Comment by mephenor** [comment]
Both parsers are now fixed in the refactoring branch, with the JSONParser now using the schema from cobrapy to create the respective objects using Jackson.
Formulae are parsed using FBC and those containing non integers are currently not supported and thus dropped.
Should they be added to notes instead?

**Comment by draeger** [comment]
As long as we are still waiting for the next FBC specification to be finalized, we should indeed keep such information (that could become valuable later on) - for now let's put it to the notes.

**Comment by mephenor** [comment]
Unparseable formulae in JSONParser are now added to the species notes.

**Comment by Schmoho** [comment]
just added a test to confirm iJB785 is parsed without error and the formula mentioned above is retained

closing and moving to tested
