### ISSUE TITLE
Improve integration with Travis using an environment variable

### ISSUE THREAD

**Issue by draeger** [draeger-lab/ModelPolisher#29]
@matthiaskoenig points out that in the `.travis.yml` file it would be essential to set an environment variable for the location of the BiGG models after performing `git clone`. This environment variable must then be used in the test cases (so that the tests know where the models are located). In the local environment, this environment variable should then be set to the location of the local models. There is also a possibility to use a caching available in Travis (in case the cloning take too long).

**Comment by mephenor** [comment]
Added environment variable MODELS to travis.

**Comment by Schmoho** [comment]
I cannot validate that the implementation as provided does serve the purpose intended back then, but since the issue is closed I am moving it to finished.
