### ISSUE TITLE
Add detailed example with steps showing ModelPolisher at work.

### ISSUE THREAD

**Issue by codekaust** [draeger-lab/ModelPolisher#32]
As the project is command-line-based, step by step procedure should be provided about how to use the ModelPolisher after building the project, also showing how output files differ from input thus helping first users identify the use of ModelPolisher for them.

**Comment by codekaust** [comment]
After building the ModelPolisher, by running the following command(in bash shell)(current directory as ModelPolisher directory) one should be able to run ModelPolisher:
`java -jar "./target/ModelPolisher-fat-1.7.jar" --input=<input> --output=<output> --annotate-with-bigg=true`

Note that input models can be found [here](https://github.com/SBRG/bigg_models_data/tree/master/models).

On running this the terminal shows these two major error:

1. `Exception in thread "main" java.lang.NullPointerException
	at edu.ucsd.sbrg.bigg.BiGGAnnotation.annotate(BiGGAnnotation.java:125)
	at edu.ucsd.sbrg.bigg.BiGGAnnotation.annotate(BiGGAnnotation.java:109)`
2. `org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"`

**Comment by mephenor** [comment]
This startup command should not yield the second error, as connection with PostgreSQL is only established if all information, i.e. host, port, dbname, user and password are given.
Could you please provide information on your database setup, as I am a bit confused as to which version of the database you are trying to connect to.
The NullPointer issue is fixed and the patch will be up in a minute.

Just to be clear, here are the two ways that should work:

PostgreSQL:
- Setup either version of the PostgreSQL database as outlined in issue #31.
- Build either jar containing the dependencies: gradle fatJar (default for just gradle) or gradle lightJar
- Start ModelPolisher with java -jar ModelPolisher-fat-1.7.jar (or ModelPolisher-noDB-1.7.jar) --input=<input> --output=<output> --annotate-with-bigg=true --host=127.0.0.1 --port=5432 --dbname=bigg --user=postgres --passwd=postgres (change accordingly, if your credentials differ from this default) 

Integrated SQLite DB:
- Build the fatJar
- Start ModelPolisher with java -jar ModelPolisher-fat-1.7.jar (or ModelPolisher-noDB-1.7.jar) --input=<input> --output=<output> --annotate-with-bigg=true

**Comment by codekaust** [comment]
Thank you @mephenor.
I was using Integrated SQLite DB with the command for PostgreSQL. I tried the correct combination and now ModelPolisher is working fine.

**Comment by codekaust** [comment]
Detailed steps have been added during various issues (#31, #57, #66) for building and running ModelPolisher.
