### ISSUE TITLE
Update ModelPolisher compatibility with openjdk-11

### ISSUE THREAD

**Issue by codekaust** [draeger-lab/ModelPolisher#34]
I was trying to polish models from https://github.com/SBRG/bigg_models_data/tree/master/models which contain `<html>` tag in them. The list can be seen by doing `grep -Ril "<html" in the `bigg_models_data/tree/master/models` directory. 

One of the examples could be `ecoli_core_model.xml`

I use the following command
```
java -jar ~/GSoC/ModelPolisher/target/ModelPolisher-fat-1.7.jar --input="/home/kaustubh/GSoC/bigg_models_data/models/ecoli_core_model.xml" --output="/home/kaustubh/Desktop/" --annotate-with-bigg=true
```

The error shown is:
`Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException`

This issue was encountered using open_jdk 11.

No issue with `java version "1.8.0_211"`

**Comment by matthiaskoenig** [comment]
Please write a more detailed issue report, so it is possible for others to reproduce the issue.

- what did you try to do? (example code, example files)
- what did go wrong?
- what did you expect to happen?

I have no idea what you tried here? Did you check a test model? If yes, which test model? What command did you run?
Without people being able to reproduce the issue it is not possible to check if it was fixed. Also no unit tests can be written for the issue.

Best Matthias

**Comment by codekaust** [comment]
@matthiaskoenig 
I just noticed that this error is coming with Java SE 9 and above only. I have updated the issue.

Probably the reason for this issue is:
 The JAXB APIs are considered to be Java EE APIs, and therefore are no longer contained on the default class path in Java SE 9. In Java 11 they are completely removed from the JDK.

**Comment by codekaust** [comment]
When using openjdk-11, the following major error comes during build:
`error: package javax.xml.bind does not exist`

Reason: According to the release-notes, Java 11 removed the Java EE modules. So, `java.xml.bind (JAXB)` - REMOVED

- Java 8 - OK
- Java 9 - DEPRECATED
- Java 10 - DEPRECATED
- Java 11 - REMOVED
