### ISSUE TITLE
Restructure ModelPolisher.

### ISSUE THREAD

**Issue by codekaust** [draeger-lab/ModelPolisher#49]
As code related to `docker` needs to be added to `ModelPolisher`, the following issue was noticed.
Currently, the `src` folder directly contains java packages, like `edu/ucsd/sbrg/` followed by code packages, which is not ideal.
Need to make the following changes:
- Move packages from current `src/` to `src/main/java/`
- Move resources from `resources/` to `src/main/resources/`
- Move test codes currently in `test/` to `src/test/java/`
- Add folder `src/main/docker/` to add code related to containeristion using docker
- Make changes accordingly to build process

**Comment by draeger** [comment]
As discussed with @matthiaskoenig, we don't need to create the folder `/src/main/docker/`, but restructuring the other locations still makes sense. In this way, the project will become more standardized and tidier.
