### ISSUE TITLE
Implement unit tests

### ISSUE THREAD

**Issue by draeger** [draeger-lab/ModelPolisher#6]
The way how this application has been tested so far was to run it on all BiGG models and validate the output, incl. check for growth. While this makes sense and tells us if the resulting model does make sense or not, individual functions actually require strict unit testing.

**Comment by mephenor** [comment]
Unit tests should be implemented while refactoring the codebase into more manageable chunks and revisiting the respective access modifiers, so we can tests functionality directly on the species/reaction/... annotation level, which is currently not possible.

**Comment by mephenor** [comment]
Closing this, as this is rather an ongoing process than a concrete issue now.
