### ISSUE TITLE
Remove SQLite version

### ISSUE THREAD

**Issue by mephenor** [draeger-lab/ModelPolisher#67]
The SQLite version of BiGGDB and all of its traces in code and configuration should be removed, as we now use Docker instead.

**Comment by codekaust** [comment]
Removed scripts and updated `build.gradle` in 64bf90f47c4b1eb81c8b1fc8aecb685e0701e217.

**Comment by codekaust** [comment]
Also removed all gradle tasks to produce different `jars`, what remains is only `lightJar`, in 64bf90f47c4b1eb81c8b1fc8aecb685e0701e217.

**Comment by codekaust** [comment]
@mephenor Any comments?

**Comment by mephenor** [comment]
There is still the SQLiteConnector class which might be removed
