### ISSUE TITLE
Make sure there is no hard dependency on AnnotateDB

### ISSUE THREAD

**Issue by mephenor** [draeger-lab/ModelPolisher#79]
The parameter combination `--annotate-with-bigg=true --add-adb-annotations=false` was reported to currently throw `edu.ucsd.sbrg.bigg.AnnotateDB getAnnotations --- WARNING: The connection attempt failed`. 
Additionally models don't seem to get much annotation.
This needs to be investigated and code touching AnnotateDB needs to be revisited.

**Comment by mephenor** [comment]
Should be fixed in the refactoring branch and already merged into master, if I am not mistaken. Need to check possible input parameter combinations for null pointer issues, however.

**Comment by Schmoho** [comment]
This issue is closed and at least the parameter combination seems to work fine for me. I'm closing the issue for the November 2019 and forward project.
