### ISSUE TITLE
Error when running with docker-compose

### ISSUE THREAD

**Issue by LisbethIsolde** [draeger-lab/ModelPolisher#82]
When using the provided docker-compose.yml file and starting according to README line 80, the container exits with an error code:
`$ docker-compose run -v $MODEL_DIR:/models/ java java -jar /ModelPolisher-2.0.jar --input=$INPUT_MODEL --output=$OUPUT_MODEL --annotate-with-bigg=true --add-adb-annotations=true --output-combine=true`<br>
`Starting modelpolisher_biggdb ... done
Starting modelpolisher_adb    ... done
Error: Unable to access jarfile /ModelPolisher-2.0.jar`

Your README is currently working with version 2.0, newer versions of the docker image mephenor/modelpolisher are using v2.0.1, mind updating line 80 in the README from ModelPolisher-2.0.jar to ModelPolisher-2.0.1.jar?

**Comment by mephenor** [comment]
Thanks for the heads up. 
The version number will now be automatically updated in the README when gradle is run.
There was a version of this implemented in the bigg-1.6 branch, but was not merged into master as the regex was not quite right. 
It is currently present in a fixed version in the refactoring branch, which will be merged into master today.
