### ISSUE TITLE
FbcPlugin and Reaction bounds/objective function/genes

### ISSUE THREAD

**Issue by Linelili** [draeger-lab/ModelPolisher#94]
When using ModelPolisher on SBML files without the fbcPlugin, the plugin is enabled. However, due to the enabling, cobraPy sometimes has difficulties reading in the correct information after that.

This mainly affects the bounds of the reactions, the objective function, and the genes. 

It would be great, if the ModelPolisher could check, whether the bounds from the unpolished model and the bounds in the fbcPlugin are the same. 

Same accounts for the objective function, which is sometimes not adopted to the polished file. 

Also sometimes genes disappear when reading in the polished model with cobraPy.

**Comment by mephenor** [comment]
Added methods to convert flux bounds and flux objectives from local parameters to FBC, if the corresponding FBC attribute is not set.
Added method to create GeneProductAssociations from reaction notes, if no association is set.
GeneProducts are created if they are not present in the model when creating the associations, so this should hopefully help with the disappearing genes.
