### ISSUE TITLE
Running with docker-compose run -u $(id -u):$(id -g) potentially locks up execution

### ISSUE THREAD

**Issue by mephenor** [draeger-lab/ModelPolisher#98]
Running the docker container as non-root consistently produces
```May 13, 2020 6:47:47 AM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode --- WARNING: Could not lock User prefs.  Unix error code 2.```
```May 13, 2020 6:47:47 AM java.util.prefs.FileSystemPreferences syncWorld --- WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.```
after random intervals of time, which potentially locks up the process indefinitely.

Creating .java/.userPrefs and .java/.systemPrefs within the container does not seem to work.

**Comment by Schmoho** [comment]
I don't see why there is a reason to run as non-root.
This is current Docker best practice: https://docs.docker.com/engine/security/userns-remap/
