### ISSUE TITLE
includeAnyURI not applied consequently across codebase

### ISSUE THREAD

**Issue by mephenor** [draeger-lab/ModelPolisher#99]
As I forgot about this Parameter when rewriting the RegistryParser and centralizing annotation handling, currently we might get a mix of MIRIAM and non MIRIAM annotations and possibly non MIRIAM annotations are missing, where they could actually be added.
As the full 2.1 release still requires cleanup and maintenance in the end and some further testing of functionality is still planned, this could be changed at the same time.

**Comment by Schmoho** [comment]
This issue is not actionable.
